# Generated by Django 5.0.3 on 2024-03-19 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('orderStatus', models.CharField(max_length=50)),
                ('shippingDetails', models.JSONField()),
                ('orderDate', models.DateField(auto_now_add=True)),
                ('orderHistory', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('productID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventoryQuantity', models.IntegerField()),
                ('details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('cellphoneNumber', models.CharField(max_length=20)),
                ('dateOfBirth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.perfume')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.user')),
                ('purchaseHistory', models.JSONField(blank=True, default=list)),
                ('browsingHistory', models.JSONField(blank=True, default=list)),
                ('recommendationList', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.user')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('savedForLater', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.user'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.perfume')),
                ('shoppingCart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.shoppingcart')),
            ],
        ),
    ]
