# Generated by Django 5.0.2 on 2024-03-20 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='perfume',
            new_name='perfumeID',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='cantidad',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderHistory',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shippingDetails',
        ),
        migrations.AddField(
            model_name='order',
            name='orderItems',
            field=models.ManyToManyField(through='store.OrderItem', to='store.perfume'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='totalPrice',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscriptionID', models.AutoField(primary_key=True, serialize=False)),
                ('subscriptionStatus', models.CharField(max_length=50)),
                ('subscriptionType', models.CharField(max_length=100)),
                ('billingDate', models.DateField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.user')),
            ],
        ),
    ]
