# Generated by Django 5.0.2 on 2024-03-20 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_perfume_orderitem_perfumeid_and_more'),
        ('store', '0007_alter_user_email'),
    ]

    operations = [
    ]
