# Generated by Django 5.0.3 on 2024-05-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommendations',
            new_name='Recommendation',
        ),
    ]
