# Generated by Django 5.0.3 on 2024-05-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_recommendations_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
