# Generated by Django 4.1 on 2024-05-19 20:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0014_subscriptionplan_alter_subscription_expirationdate_and_more"),
    ]

    operations = []
